---
title: "GEO数据库挖掘(2)之数据整合"
author:
  - 阎俊安 2022-01-17
documentclass: ctexart
keywords:
  - ggplot2

geometry: "left=2cm,right=2cm,top=2cm,bottom=2cm"
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
---

本节来介绍如何使用**GEO**数据库进行数据挖掘，请参考前文**一文搞定GEO数据下载**

# 安装并加载R包

```{r,eval=FALSE}

package.list=c("tidyverse","GEOquery","magrittr")

for (package in package.list) {
  if (!require(package,character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}
```

# 导入数据

```{r,eval=FALSE}
load(file ="GSE33126.rdata")

gset <- gset[[1]]
class(gset)
```

# 样本信息表
```{r,eval=FALSE}
sampleinfo <- pData(gset) %>%# 提取样本信息表
  select(source_name_ch1,characteristics_ch1.1) %>% 
  rename(group = source_name_ch1,patient=characteristics_ch1.1) %>% 
  mutate_at(vars(patient),~str_split(.," ",simplify = T)[,2])
```

# 基因表达矩阵
```{r,eval=FALSE}
gene_exp <- exprs(gset) %>% as.data.frame()
```

# 检查探针编号
```{r,eval=FALSE}
tail(gene_exp[,1:3])
```

# 同步表达矩阵与样本信息
```{r,eval=FALSE}
gene_exp <- gene_exp[,which(
  colnames(gene_exp) %in% rownames(sampleinfo)
)]
```

* 查看数据
```{r,eval=FALSE}
summary(gene_exp)
gene_exp <- log2(gene_exp)
```
* 绘制箱线图
```{r,eval=FALSE}
boxplot(gene_exp,outline=FALSE)
```
若箱线图中位数差异较大可以执行下面代码对数据进行标准化处理

* 对数据进行标准化
```{r,eval=FALSE}
library(limma)
p <- as.data.frame(
  normalizeBetweenArrays(gene_exp)
)
```
经过上面的步骤我们得到了样本信息表 & 基因表达矩阵信息表，接下来从**GEO**数据库下载基因信息表就可进行后续分析

# 整合基因信息表
```{r,eval=FALSE}
gene_info <- read_delim("GPL6947-13512.txt", "\t",escape_double = FALSE, comment = "#", 
                        trim_ws = TRUE) %>%
  dplyr::select(ID,Gene_Symbol = Symbol,Entrez_Gene_ID, 
                Gene_Title = Definition) %>% drop_na()
```
现在我们得到了分析需要的3张表，**save**将其保存后续分析直接加载即可

```{r,eval=FALSE}
save(gene_exp,sampleinfo,gene_info, file='GSE33126-info.rdata')
```